/**
 * Default pre-use checklist templates per equipment type.
 * These are seeded into equipment_checklist_templates with company_id = NULL.
 * Companies can override by creating their own row for a type.
 */

export const EQUIPMENT_TYPES = [
  // Access Equipment
  { value: 'MEWP - Scissor Lift', label: 'MEWP — Scissor Lift', group: 'Access Equipment' },
  { value: 'MEWP - Boom Lift', label: 'MEWP — Boom Lift', group: 'Access Equipment' },
  { value: 'MEWP - Cherry Picker', label: 'MEWP — Cherry Picker', group: 'Access Equipment' },
  { value: 'MEWP - Spider Lift', label: 'MEWP — Spider Lift', group: 'Access Equipment' },
  { value: 'Scaffold Tower', label: 'Scaffold Tower', group: 'Access Equipment' },
  { value: 'Podium', label: 'Podium Steps', group: 'Access Equipment' },
  { value: 'Step Ladder', label: 'Step Ladder', group: 'Access Equipment' },
  { value: 'Extension Ladder', label: 'Extension Ladder', group: 'Access Equipment' },
  { value: 'Roof Ladder', label: 'Roof Ladder', group: 'Access Equipment' },
  { value: 'Hop-Up Platform', label: 'Hop-Up Platform', group: 'Access Equipment' },
  { value: 'Trestle', label: 'Trestle', group: 'Access Equipment' },
  // Lifting
  { value: 'Hoist', label: 'Hoist', group: 'Lifting Equipment' },
  { value: 'Chain Block', label: 'Chain Block', group: 'Lifting Equipment' },
  { value: 'Lifting Beam', label: 'Lifting Beam', group: 'Lifting Equipment' },
  { value: 'Sling', label: 'Sling / Strop', group: 'Lifting Equipment' },
  { value: 'Shackle', label: 'Shackle', group: 'Lifting Equipment' },
  // Power Tools
  { value: 'Drill', label: 'Drill', group: 'Power Tools' },
  { value: 'Angle Grinder', label: 'Angle Grinder', group: 'Power Tools' },
  { value: 'Circular Saw', label: 'Circular Saw', group: 'Power Tools' },
  { value: 'Reciprocating Saw', label: 'Reciprocating Saw', group: 'Power Tools' },
  { value: 'SDS Drill', label: 'SDS / Hammer Drill', group: 'Power Tools' },
  { value: 'Chop Saw', label: 'Chop Saw', group: 'Power Tools' },
  { value: 'Jigsaw', label: 'Jigsaw', group: 'Power Tools' },
  { value: 'Power Tool - Other', label: 'Power Tool — Other', group: 'Power Tools' },
  // Electrical
  { value: 'Temp Electrics', label: 'Temporary Distribution Board', group: 'Electrical' },
  { value: 'Transformer', label: 'Transformer (110V)', group: 'Electrical' },
  { value: 'Extension Lead', label: 'Extension Lead', group: 'Electrical' },
  { value: 'Festoon Lighting', label: 'Festoon / Temp Lighting', group: 'Electrical' },
  // Safety
  { value: 'Fire Extinguisher', label: 'Fire Extinguisher', group: 'Fire & Safety' },
  { value: 'First Aid Kit', label: 'First Aid Kit', group: 'Fire & Safety' },
  { value: 'Spill Kit', label: 'Spill Kit', group: 'Fire & Safety' },
  { value: 'Harness', label: 'Safety Harness', group: 'Fire & Safety' },
  { value: 'Lanyard', label: 'Lanyard / Fall Arrest', group: 'Fire & Safety' },
  // General
  { value: 'Generator', label: 'Generator', group: 'General Plant' },
  { value: 'Compressor', label: 'Compressor', group: 'General Plant' },
  { value: 'Dehumidifier', label: 'Dehumidifier', group: 'General Plant' },
  { value: 'Fan', label: 'Ventilation Fan', group: 'General Plant' },
  { value: 'Pump', label: 'Pump', group: 'General Plant' },
  { value: 'Other', label: 'Other', group: 'General Plant' },
]

export const DEFAULT_CHECKLISTS = {
  // MEWP variants share the same checklist
  'MEWP - Scissor Lift': [
    'Outriggers / stabilisers deployed and locked',
    'Guardrails secure and undamaged',
    'Emergency lowering tested',
    'Battery charge adequate',
    'Ground conditions stable and level',
    'Controls responsive and correct',
    'Safety harness anchor points checked',
    'No visible damage, leaks, or corrosion',
    'Horn / alarm functional',
    'Wheels / tyres in good condition',
  ],
  'MEWP - Boom Lift': [
    'Outriggers / stabilisers deployed and locked',
    'Guardrails secure and undamaged',
    'Emergency lowering tested',
    'Battery / fuel level adequate',
    'Ground conditions stable and level',
    'Controls responsive and correct',
    'Safety harness anchor points checked',
    'No visible damage, leaks, or corrosion',
    'Horn / alarm functional',
    'Boom sections move freely',
  ],
  'MEWP - Cherry Picker': [
    'Outriggers / stabilisers deployed and locked',
    'Guardrails and basket secure',
    'Emergency lowering tested',
    'Fuel / battery level adequate',
    'Ground conditions stable and level',
    'Controls responsive and correct',
    'Safety harness anchor points checked',
    'No visible damage, leaks, or corrosion',
  ],
  'MEWP - Spider Lift': [
    'Outriggers deployed and locked',
    'Guardrails and basket secure',
    'Emergency lowering tested',
    'Battery charge adequate',
    'Ground conditions stable and level',
    'Controls responsive and correct',
    'Safety harness anchor points checked',
    'No visible damage or leaks',
    'Tracks / wheels in good condition',
  ],
  'Scaffold Tower': [
    'Base plates or castors locked',
    'All braces in place and secure',
    'Platform boards secure with no gaps',
    'Toe boards fitted',
    'Guardrails at correct height',
    'No visible damage or corrosion',
    'Scaffold tag in date',
    'Outriggers deployed if required',
  ],
  'Podium': [
    'Platform locked in position',
    'Wheels locked',
    'Guardrails secure',
    'No visible damage or cracks',
    'Steps secure and non-slip',
  ],
  'Step Ladder': [
    'Feet / rubber pads intact',
    'No cracks, bends, or damage',
    'Locking mechanism works',
    'Rungs clean and non-slip',
    'Correct height for task',
  ],
  'Extension Ladder': [
    'Feet / rubber pads intact',
    'No cracks, bends, or damage',
    'Rung locks engage properly',
    'Rungs clean and non-slip',
    'Rope / pulley in good condition',
    'Secured at top or footed by second person',
  ],
  'Roof Ladder': [
    'Hook secure and undamaged',
    'Rungs clean and non-slip',
    'No cracks, bends, or damage',
    'Ridge fitting secure',
  ],
  'Hop-Up Platform': [
    'Platform stable and level',
    'No visible cracks or damage',
    'Non-slip surface intact',
    'Legs / feet secure',
  ],
  'Trestle': [
    'Legs lock securely',
    'No visible damage or bends',
    'Feet / pads intact',
    'Boards secure if used as staging',
  ],
  // Lifting
  'Hoist': [
    'Wire rope / chain in good condition',
    'Hook and safety catch functional',
    'Brakes working correctly',
    'LOLER examination in date',
    'SWL clearly marked',
    'No visible damage or corrosion',
  ],
  'Chain Block': [
    'Chain links undamaged',
    'Hook and safety catch functional',
    'Brakes hold load securely',
    'LOLER examination in date',
    'SWL clearly marked',
  ],
  'Lifting Beam': [
    'No visible cracks or deformation',
    'Shackle points undamaged',
    'LOLER examination in date',
    'SWL clearly marked',
    'Painted / marked correctly',
  ],
  'Sling': [
    'No cuts, abrasion, or damage to webbing',
    'Stitching intact',
    'Label legible with SWL',
    'LOLER examination in date',
    'No knots or twists',
  ],
  'Shackle': [
    'Pin threads freely',
    'No visible cracks or deformation',
    'SWL clearly marked',
    'Correct type for load',
  ],
  // Power Tools
  'Drill': ['Cable and plug undamaged', 'Chuck tightens securely', 'Trigger / switch functional', 'PAT test in date', 'Guard in place if applicable'],
  'Angle Grinder': ['Cable and plug undamaged', 'Guard in place and secure', 'Disc in good condition and correct type', 'Trigger / switch functional', 'PAT test in date', 'Handle secure'],
  'Circular Saw': ['Cable and plug undamaged', 'Guard retracts and returns correctly', 'Blade in good condition', 'Trigger / switch functional', 'PAT test in date', 'Rip fence / guide secure'],
  'Reciprocating Saw': ['Cable / battery in good condition', 'Blade secure and correct type', 'Trigger / switch functional', 'PAT test in date', 'Shoe plate undamaged'],
  'SDS Drill': ['Cable and plug undamaged', 'Chuck / bit holder secure', 'Mode selector works', 'Trigger / switch functional', 'PAT test in date', 'Side handle secure'],
  'Chop Saw': ['Cable and plug undamaged', 'Guard in place and returns', 'Blade in good condition', 'Clamp holds material securely', 'PAT test in date', 'Fence square and secure'],
  'Jigsaw': ['Cable / battery in good condition', 'Blade secure', 'Trigger / switch functional', 'PAT test in date', 'Base plate secure'],
  'Power Tool - Other': ['Cable and plug undamaged', 'Guard in place and secure', 'PAT test in date', 'Trigger / switch functional', 'No visible damage'],
  // Electrical
  'Temp Electrics': [
    'RCD tested and functional',
    'Cables undamaged and routed safely',
    'All connections secure',
    'Distribution board door closes and locks',
    'No signs of overheating or burning',
    'Labels legible and correct',
    'Earth bonding intact',
  ],
  'Transformer': ['Casing undamaged', 'Cables and connections secure', 'Ventilation clear', 'PAT test in date', 'Output sockets functional'],
  'Extension Lead': ['Cable undamaged along full length', 'Plug and socket undamaged', 'PAT test in date', 'No signs of overheating', 'Fully unwound when in use'],
  'Festoon Lighting': ['Cable undamaged', 'All lamp holders secure', 'Guards in place on each lamp', 'PAT test in date', 'Suspension points secure'],
  // Safety
  'Fire Extinguisher': [
    'Pin intact and sealed',
    'Pressure gauge in green zone',
    'No visible damage or corrosion',
    'Service tag in date',
    'Nozzle clear and undamaged',
    'Correct type for area',
  ],
  'First Aid Kit': ['Contents complete and in date', 'Box clean and undamaged', 'Location sign visible', 'Responsible person identified'],
  'Spill Kit': ['Contents complete', 'Bag / container undamaged', 'Correct type for substances present', 'Location accessible'],
  'Harness': [
    'Webbing undamaged — no cuts, fraying, or burns',
    'Buckles and D-rings undamaged',
    'Stitching intact',
    'Label legible with inspection date',
    'Thorough examination in date',
  ],
  'Lanyard': [
    'Webbing / rope undamaged',
    'Karabiners lock correctly',
    'Shock absorber pack undamaged',
    'Label legible with inspection date',
    'Thorough examination in date',
  ],
  // General
  'Generator': ['Fuel level adequate', 'Oil level checked', 'Exhaust clear and ventilated', 'Earth bonding intact', 'Output sockets functional', 'No visible damage or leaks'],
  'Compressor': ['Oil level adequate', 'Pressure gauge functional', 'Hoses undamaged', 'Safety valve functional', 'No visible damage or leaks'],
  'Dehumidifier': ['Filter clean', 'Drain hose connected', 'No visible damage', 'Power cable undamaged'],
  'Fan': ['Guard in place', 'Blades undamaged', 'Power cable undamaged', 'Stable base'],
  'Pump': ['Hoses undamaged and connected', 'Power cable undamaged', 'No visible leaks', 'Primed correctly'],
  'Other': ['General visual inspection passed', 'No visible damage', 'Safe to use'],
}

export const EQUIPMENT_STATUSES = [
  { value: 'In Service', label: 'In Service', color: '#2C9C5E' },
  { value: 'Defective', label: 'Defective', color: '#D93E3E' },
  { value: 'Off-Site', label: 'Off-Site', color: '#D29922' },
  { value: 'Off-Hire', label: 'Off-Hire', color: '#7C828F' },
]

export const DEFECT_SEVERITIES = [
  { value: 'Minor', label: 'Minor', color: '#D29922' },
  { value: 'Major', label: 'Major', color: '#EA580C' },
  { value: 'Critical', label: 'Critical', color: '#D93E3E' },
]
