/**
 * CoreSite Procurement Schedule — Excel Export/Import
 */

import ExcelJS from 'exceljs'
import {
  computeMilestones, parseLeadTime, fmtDate, fmtDateISO, parseDate,
} from './procurementSchedule'

// ── Brand colours ──
const NAVY = 'FF0D1426'
const NAVY2 = 'FF16213B'
const BLUE = 'FF1B6FC8'
const BLUE_SOFT = 'FFE9F1FB'
const GREEN = 'FF2C9C5E'
const GREEN_SOFT = 'FFE7F5EC'
const RED = 'FFD93E3E'
const RED_SOFT = 'FFFDECEC'
const WHITE = 'FFFFFFFF'
const PAPER = 'FFFFFFFF'
const PAPER2 = 'FFF5F7FA'
const INK = 'FF0D1426'
const INK2 = 'FF3A4254'
const MUTED = 'FF7C828F'
const MUTED2 = 'FFA2A7B2'
const LINE = 'FFE8EBF1'
const YELLOW_BG = 'FFFFFBEB'

const FONT = 'Calibri'
const HEADER_ROW = 9
const DATA_START = 11

function thinBorder(color = LINE) {
  return { style: 'thin', color: { argb: color } }
}

export async function exportToExcel(header, rules, rows) {
  const wb = new ExcelJS.Workbook()
  wb.creator = 'CoreSite'
  wb.created = new Date()
  const ws = wb.addWorksheet(header.trade || 'Procurement Schedule', {
    pageSetup: { paperSize: 8, orientation: 'landscape', fitToPage: true, fitToWidth: 1, fitToHeight: 0 },
  })

  // ── Row 1: Title banner (merged A1:M1) ──
  ws.mergeCells('A1:M1')
  const titleCell = ws.getCell('A1')
  titleCell.value = 'PROCUREMENT SCHEDULE'
  titleCell.font = { bold: true, size: 16, name: FONT, color: { argb: WHITE } }
  titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } }
  titleCell.alignment = { vertical: 'middle', horizontal: 'left', indent: 1 }
  ws.getRow(1).height = 36

  // ── Row 2: Subtitle / company line ──
  ws.mergeCells('A2:M2')
  const subCell = ws.getCell('A2')
  subCell.value = 'Generated by CoreSite — Site Compliance Platform'
  subCell.font = { size: 9, name: FONT, color: { argb: MUTED2 } }
  subCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY2 } }
  subCell.alignment = { vertical: 'middle', horizontal: 'left', indent: 1 }
  ws.getRow(2).height = 20

  // Blue accent line (row 3)
  ws.mergeCells('A3:M3')
  ws.getCell('A3').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BLUE } }
  ws.getRow(3).height = 3

  // ── Rows 4-7: Project details (two-column layout) ──
  const details = [
    ['Project', header.project || '', 'Project No.', header.projectNo || ''],
    ['Stage', header.stage || '', 'Revision', header.revision || ''],
    ['Trade', header.trade || '', 'Date', header.date || fmtDateISO(new Date())],
  ]

  details.forEach((row, i) => {
    const r = i + 4
    // Left pair
    ws.getCell(r, 1).value = row[0]
    ws.getCell(r, 1).font = { size: 9, name: FONT, color: { argb: MUTED }, bold: true }
    ws.getCell(r, 1).alignment = { vertical: 'middle' }
    ws.mergeCells(r, 2, r, 5)
    ws.getCell(r, 2).value = row[1]
    ws.getCell(r, 2).font = { size: 11, name: FONT, color: { argb: INK }, bold: true }
    ws.getCell(r, 2).alignment = { vertical: 'middle' }
    // Right pair
    ws.getCell(r, 7).value = row[2]
    ws.getCell(r, 7).font = { size: 9, name: FONT, color: { argb: MUTED }, bold: true }
    ws.getCell(r, 7).alignment = { vertical: 'middle' }
    ws.mergeCells(r, 8, r, 10)
    ws.getCell(r, 8).value = row[3]
    ws.getCell(r, 8).font = { size: 11, name: FONT, color: { argb: INK } }
    ws.getCell(r, 8).alignment = { vertical: 'middle' }
    ws.getRow(r).height = 20
  })

  // ── Row 7: Spacer ──
  ws.getRow(7).height = 8

  // Columns N-P kept empty (no scheduling rules in export)

  // ── Row 8: Spacer ──
  ws.getRow(8).height = 6

  // ── Row 9: Column headers ──
  const headers = ['Description', 'Supplier', 'Level', 'Tech Sub Issue', 'Approval Required',
    'Date Approved', 'Status (A|B|C)', 'Order Placed', 'Lead Time', 'Delivery Required',
    'Required On Site', 'Comments']

  // Calculated column indices (0-based): 3=TechSub, 4=Approval, 7=Order, 9=Delivery
  const calcCols = [3, 4, 7, 9]

  headers.forEach((h, i) => {
    const cell = ws.getCell(HEADER_ROW, i + 1)
    cell.value = h
    cell.font = { bold: true, size: 10, name: FONT, color: { argb: WHITE } }
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } }
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true }
    cell.border = {
      bottom: { style: 'medium', color: { argb: BLUE } },
      left: thinBorder(NAVY2),
      right: thinBorder(NAVY2),
    }
  })
  ws.getRow(HEADER_ROW).height = 28

  // Sub-header hint row (row 10)
  const hints = ['User input', 'User input', 'User input', 'Auto', 'Auto',
    'User input', 'User input', 'Auto', 'User input', 'Auto',
    'User input', 'User input']
  hints.forEach((h, i) => {
    const cell = ws.getCell(HEADER_ROW + 1, i + 1)
    cell.value = h
    const isAuto = h === 'Auto'
    cell.font = { size: 8, name: FONT, italic: true, color: { argb: isAuto ? BLUE : MUTED } }
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: isAuto ? BLUE_SOFT : PAPER2 } }
    cell.alignment = { vertical: 'middle', horizontal: 'center' }
    cell.border = { bottom: { style: 'medium', color: { argb: LINE } } }
  })
  ws.getRow(HEADER_ROW + 1).height = 16

  // Hidden helper column Q
  ws.getCell(HEADER_ROW, 17).value = 'LW'
  ws.getCell(HEADER_ROW, 17).font = { size: 8, name: FONT, color: { argb: MUTED2 } }

  // ── Column widths ──
  ws.getColumn(1).width = 34   // Description
  ws.getColumn(2).width = 20   // Supplier
  ws.getColumn(3).width = 8    // Level
  ws.getColumn(4).width = 14   // Tech Sub
  ws.getColumn(5).width = 14   // Approval
  ws.getColumn(6).width = 14   // Date Approved
  ws.getColumn(7).width = 14   // Status
  ws.getColumn(8).width = 14   // Order Placed
  ws.getColumn(9).width = 10   // Lead Time
  ws.getColumn(10).width = 14  // Delivery
  ws.getColumn(11).width = 14  // Req On Site
  ws.getColumn(12).width = 28  // Comments
  ws.getColumn(13).width = 2   // Spacer
  ws.getColumn(14).width = 22  // Algo label
  ws.getColumn(15).width = 6   // Algo label cont
  ws.getColumn(16).width = 10  // Algo value
  ws.getColumn(17).width = 5   // Helper (hidden)
  ws.getColumn(17).hidden = true

  // ── Data rows (starting at DATA_START = 11) ──
  const today = new Date(); today.setHours(0, 0, 0, 0)

  rows.forEach((row, i) => {
    const r = DATA_START + i
    const lw = parseLeadTime(row.leadTime)
    const ms = lw && row.requiredOnSite ? computeMilestones(row.requiredOnSite, lw, { deliveryWeeksBefore: rules.deliveryWeeksBefore, techSubDaysBefore: rules.techSubDaysBefore, techSubDaysType: rules.techSubDaysType }) : null
    const statusStr = ['a', 'b', 'c'].map(k => {
      const v = row.status?.[k]
      return v === 'yes' ? '✓' : v === 'no' ? '✗' : ''
    }).join(' | ')

    // Col A: Description
    ws.getCell(r, 1).value = row.description || ''
    // Col B: Supplier
    ws.getCell(r, 2).value = row.supplier || ''
    // Col C: Level
    ws.getCell(r, 3).value = row.firstLevel || ''
    ws.getCell(r, 3).alignment = { horizontal: 'center', vertical: 'middle' }
    // Col D: Tech Sub (formula)
    ws.getCell(r, 4).value = ms ? ms.techSubIssue : ''
    if (ms) ws.getCell(r, 4).numFmt = 'DD MMM YYYY'
    // Col E: Approval (formula)
    ws.getCell(r, 5).value = ms ? ms.approvalRequired : ''
    if (ms) ws.getCell(r, 5).numFmt = 'DD MMM YYYY'
    // Col F: Date Approved
    ws.getCell(r, 6).value = row.dateApproved ? new Date(row.dateApproved) : ''
    ws.getCell(r, 6).numFmt = 'DD MMM YYYY'
    // Col G: Status
    ws.getCell(r, 7).value = statusStr
    ws.getCell(r, 7).alignment = { horizontal: 'center', vertical: 'middle' }
    // Col H: Order Placed (formula)
    ws.getCell(r, 8).value = ms ? ms.orderPlaced : ''
    if (ms) ws.getCell(r, 8).numFmt = 'DD MMM YYYY'
    // Col I: Lead Time
    ws.getCell(r, 9).value = row.leadTime || ''
    ws.getCell(r, 9).alignment = { horizontal: 'center', vertical: 'middle' }
    // Col J: Delivery (formula)
    ws.getCell(r, 10).value = ms ? ms.delivery : ''
    if (ms) ws.getCell(r, 10).numFmt = 'DD MMM YYYY'
    // Col K: Required On Site
    ws.getCell(r, 11).value = row.requiredOnSite ? new Date(row.requiredOnSite) : ''
    ws.getCell(r, 11).numFmt = 'DD MMM YYYY'
    // Col L: Comments
    ws.getCell(r, 12).value = row.comments || ''

    // Styling
    const stripe = i % 2 === 1
    ws.getRow(r).height = 22

    for (let c = 1; c <= 12; c++) {
      const cell = ws.getCell(r, c)
      const isCalc = calcCols.includes(c - 1)
      const dateVal = isCalc && ms ? [ms.techSubIssue, ms.approvalRequired, null, null, ms.orderPlaced, null, ms.delivery][c - 4] : null
      const isPast = dateVal && dateVal < today

      // Font
      if (isCalc) {
        cell.font = { size: 10, name: FONT, color: { argb: isPast ? RED : BLUE }, bold: true }
      } else {
        cell.font = { size: 10, name: FONT, color: { argb: INK } }
      }

      // Fill
      if (isPast) {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: RED_SOFT } }
      } else if (isCalc && ms) {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BLUE_SOFT } }
      } else if (stripe) {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: PAPER2 } }
      }

      // Borders
      cell.border = {
        bottom: thinBorder(),
        right: thinBorder(),
        left: c === 1 ? thinBorder() : undefined,
      }
      if (!cell.alignment) cell.alignment = { vertical: 'middle' }
    }
  })

  // ── Freeze panes ──
  ws.views = [{ state: 'frozen', xSplit: 1, ySplit: HEADER_ROW + 1, topLeftCell: `B${DATA_START}` }]

  // ── Print area ──
  const lastRow = Math.max(DATA_START, DATA_START + rows.length - 1)
  ws.pageSetup.printArea = `A1:L${lastRow}`

  // ── Footer text ──
  const footerRow = lastRow + 2
  ws.mergeCells(footerRow, 1, footerRow, 12)
  ws.getCell(footerRow, 1).value = `Generated by CoreSite · ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`
  ws.getCell(footerRow, 1).font = { size: 8, name: FONT, color: { argb: MUTED2 }, italic: true }
  ws.getCell(footerRow, 1).alignment = { horizontal: 'right' }

  // ── Save ──
  const buf = await wb.xlsx.writeBuffer()
  const blob = new Blob([buf], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${header.projectNo || 'CoreSite'}_${header.trade || 'Procurement'}_Schedule_Rev${header.revision || ''}_${fmtDateISO(new Date())}.xlsx`
  a.click()
  URL.revokeObjectURL(url)
}

// ── Import ──

export async function importFromExcel(file) {
  const wb = new ExcelJS.Workbook()
  const buf = await file.arrayBuffer()
  await wb.xlsx.load(buf)

  const ws = wb.worksheets[0]
  if (!ws) return null

  const header = {}
  const fieldMap = { 'Project:': 'project', 'Project': 'project', 'Stage:': 'stage', 'Stage': 'stage', 'Project No:': 'projectNo', 'Project No.': 'projectNo', 'Revision:': 'revision', 'Revision': 'revision', 'Date:': 'date', 'Date': 'date', 'Trade:': 'trade', 'Trade': 'trade' }
  for (let r = 1; r <= 8; r++) {
    for (let c = 1; c <= 2; c++) {
      const label = String(ws.getCell(r, c).value || '').trim()
      const key = fieldMap[label]
      if (key) {
        let val = ws.getCell(r, c + 1).value || ws.getCell(r, c + 4).value
        if (val instanceof Date) val = fmtDateISO(val)
        if (val) header[key] = String(val)
      }
    }
  }

  const rules = {}
  const ruleKeys = ['deliveryWeeksBefore', 'orderPlacedWeekday', 'approvalWeekday', 'techSubDaysBefore', 'techSubWeekday']
  for (let r = 3; r <= 7; r++) {
    const val = ws.getCell(r, 16)?.value
    if (val != null) {
      const num = typeof val === 'object' && val.result != null ? val.result : val
      rules[ruleKeys[r - 3]] = parseInt(num) || 0
    }
  }

  // Find header row (look for "Description" in column A)
  let dataStart = DATA_START
  for (let r = 8; r <= 12; r++) {
    const v = String(ws.getCell(r, 1).value || '').toLowerCase()
    if (v.includes('description')) { dataStart = r + 2; break }
  }

  const rows = []
  let r = dataStart
  while (r < 500) {
    const desc = ws.getCell(r, 1).value
    if (desc == null || desc === '') break

    let onSiteVal = ws.getCell(r, 11).value
    if (onSiteVal instanceof Date) onSiteVal = fmtDateISO(onSiteVal)
    else if (typeof onSiteVal === 'object' && onSiteVal?.result instanceof Date) onSiteVal = fmtDateISO(onSiteVal.result)

    let approvedVal = ws.getCell(r, 6).value
    if (approvedVal instanceof Date) approvedVal = fmtDateISO(approvedVal)
    else if (typeof approvedVal === 'object' && approvedVal?.result instanceof Date) approvedVal = fmtDateISO(approvedVal.result)

    const statusRaw = String(ws.getCell(r, 7).value || '')
    const statusParts = statusRaw.split('|').map(s => s.trim())
    const status = {
      a: statusParts[0] === '✓' ? 'yes' : statusParts[0] === '✗' ? 'no' : null,
      b: statusParts[1] === '✓' ? 'yes' : statusParts[1] === '✗' ? 'no' : null,
      c: statusParts[2] === '✓' ? 'yes' : statusParts[2] === '✗' ? 'no' : null,
    }

    rows.push({
      id: rows.length + 1,
      description: String(desc || ''),
      supplier: String(ws.getCell(r, 2).value || ''),
      firstLevel: String(ws.getCell(r, 3).value || ''),
      leadTime: String(ws.getCell(r, 9).value || ''),
      requiredOnSite: onSiteVal || '',
      dateApproved: approvedVal || '',
      status,
      comments: String(ws.getCell(r, 12).value || ''),
      category: 'General',
    })
    r++
  }

  return { header, rules, rows }
}
